-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.carrito
(
    id_carrito serial NOT NULL,
    id_cliente integer NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT carrito_pkey PRIMARY KEY (id_carrito)
);

CREATE TABLE IF NOT EXISTS public.ciudad
(
    id_ciudad serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_pais integer NOT NULL,
    CONSTRAINT ciudad_pkey PRIMARY KEY (id_ciudad)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    id_cliente serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    id_suscripcion integer,
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente),
    CONSTRAINT cliente_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.comercio
(
    id_comercio serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rubro character varying(50) COLLATE pg_catalog."default",
    direccion character varying(200) COLLATE pg_catalog."default",
    latitud numeric(10, 8),
    longitud numeric(11, 8),
    id_ciudad integer,
    CONSTRAINT comercio_pkey PRIMARY KEY (id_comercio)
);

CREATE TABLE IF NOT EXISTS public.complemento
(
    id_complemento serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    precio_extra numeric(10, 2),
    CONSTRAINT complemento_pkey PRIMARY KEY (id_complemento)
);

CREATE TABLE IF NOT EXISTS public.cupon
(
    id_cupon serial NOT NULL,
    codigo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    porcentaje numeric(5, 2) NOT NULL,
    fecha_expira date NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT cupon_pkey PRIMARY KEY (id_cupon),
    CONSTRAINT cupon_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.detalle_pedido
(
    id_detalle serial NOT NULL,
    id_pedido integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    CONSTRAINT detalle_pedido_pkey PRIMARY KEY (id_detalle)
);

CREATE TABLE IF NOT EXISTS public.direccion
(
    id_direccion serial NOT NULL,
    id_cliente integer NOT NULL,
    calle character varying(150) COLLATE pg_catalog."default" NOT NULL,
    numero character varying(20) COLLATE pg_catalog."default",
    latitud numeric(10, 8),
    longitud numeric(11, 8),
    id_ciudad integer,
    CONSTRAINT direccion_pkey PRIMARY KEY (id_direccion)
);

CREATE TABLE IF NOT EXISTS public.item_carrito
(
    id_item serial NOT NULL,
    id_carrito integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad integer NOT NULL,
    CONSTRAINT item_carrito_pkey PRIMARY KEY (id_item)
);

CREATE TABLE IF NOT EXISTS public.item_carrito_complemento
(
    id_item_carrito_complemento serial NOT NULL,
    id_item_carrito integer NOT NULL,
    id_complemento integer NOT NULL,
    CONSTRAINT item_carrito_complemento_pkey PRIMARY KEY (id_item_carrito_complemento)
);

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pago serial NOT NULL,
    id_pedido integer NOT NULL,
    metodo_pago character varying(50) COLLATE pg_catalog."default",
    monto_final numeric(10, 2) NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default",
    fecha_pago timestamp without time zone,
    CONSTRAINT pago_pkey PRIMARY KEY (id_pago)
);

CREATE TABLE IF NOT EXISTS public.pais
(
    id_pais serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pais_pkey PRIMARY KEY (id_pais)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    id_pedido serial NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    total_productos numeric(10, 2) NOT NULL,
    costo_envio numeric(10, 2) NOT NULL,
    distancia_km numeric(6, 2),
    id_cliente integer NOT NULL,
    id_comercio integer NOT NULL,
    id_repartidor integer,
    id_cupon integer,
    CONSTRAINT pedido_pkey PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    id_producto serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    precio numeric(10, 2) NOT NULL,
    id_comercio integer NOT NULL,
    CONSTRAINT producto_pkey PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.reclamo
(
    id_reclamo serial NOT NULL,
    id_pedido integer NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT reclamo_pkey PRIMARY KEY (id_reclamo)
);

CREATE TABLE IF NOT EXISTS public.repartidor
(
    id_repartidor serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    vehiculo character varying(50) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    calificacion_promedio numeric(3, 2),
    id_ciudad integer,
    CONSTRAINT repartidor_pkey PRIMARY KEY (id_repartidor)
);

CREATE TABLE IF NOT EXISTS public.suscripcion
(
    id_suscripcion serial NOT NULL,
    tipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    costo_mensual numeric(10, 2) NOT NULL,
    descuento_envio numeric(5, 2) NOT NULL,
    CONSTRAINT suscripcion_pkey PRIMARY KEY (id_suscripcion)
);

CREATE TABLE IF NOT EXISTS public.valoracion_pedido
(
    id_valoracion serial NOT NULL,
    id_pedido integer NOT NULL,
    nota_comercio integer,
    nota_repartidor integer,
    comentario text COLLATE pg_catalog."default",
    fecha_valoracion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT valoracion_pedido_pkey PRIMARY KEY (id_valoracion),
    CONSTRAINT valoracion_pedido_id_pedido_key UNIQUE (id_pedido)
);

ALTER TABLE IF EXISTS public.carrito
    ADD CONSTRAINT carrito_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ciudad
    ADD CONSTRAINT fk_pais FOREIGN KEY (id_pais)
    REFERENCES public.pais (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT cliente_id_suscripcion_fkey FOREIGN KEY (id_suscripcion)
    REFERENCES public.suscripcion (id_suscripcion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comercio
    ADD CONSTRAINT fk_ciudad_comercio FOREIGN KEY (id_ciudad)
    REFERENCES public.ciudad (id_ciudad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.detalle_pedido
    ADD CONSTRAINT detalle_pedido_id_pedido_fkey FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_pedido
    ADD CONSTRAINT detalle_pedido_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.producto (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.direccion
    ADD CONSTRAINT direccion_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.direccion
    ADD CONSTRAINT fk_ciudad_direccion FOREIGN KEY (id_ciudad)
    REFERENCES public.ciudad (id_ciudad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.item_carrito
    ADD CONSTRAINT item_carrito_id_carrito_fkey FOREIGN KEY (id_carrito)
    REFERENCES public.carrito (id_carrito) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.item_carrito
    ADD CONSTRAINT item_carrito_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.producto (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.item_carrito_complemento
    ADD CONSTRAINT fk_complemento FOREIGN KEY (id_complemento)
    REFERENCES public.complemento (id_complemento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.item_carrito_complemento
    ADD CONSTRAINT fk_item_carrito FOREIGN KEY (id_item_carrito)
    REFERENCES public.item_carrito (id_item) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT pago_id_pedido_fkey FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT pedido_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT pedido_id_comercio_fkey FOREIGN KEY (id_comercio)
    REFERENCES public.comercio (id_comercio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT pedido_id_cupon_fkey FOREIGN KEY (id_cupon)
    REFERENCES public.cupon (id_cupon) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT pedido_id_repartidor_fkey FOREIGN KEY (id_repartidor)
    REFERENCES public.repartidor (id_repartidor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_id_comercio_fkey FOREIGN KEY (id_comercio)
    REFERENCES public.comercio (id_comercio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reclamo
    ADD CONSTRAINT reclamo_id_pedido_fkey FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.repartidor
    ADD CONSTRAINT fk_ciudad_repartidor FOREIGN KEY (id_ciudad)
    REFERENCES public.ciudad (id_ciudad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.valoracion_pedido
    ADD CONSTRAINT valoracion_pedido_id_pedido_fkey FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS valoracion_pedido_id_pedido_key
    ON public.valoracion_pedido(id_pedido);

END;